import type { Metadata } from "next";
import { ViewTransition } from 'react'
// import { DM_Serif_Text } from "next/font/google";
import "./globals.css";

//agregar otra fuente mas amigable visualmente
// const DST = DM_Serif_Text({
//   subsets: ["latin"], weight: "400"
// });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${DST.className} antialiased`}
      >
        <ViewTransition>
          {children}
        </ViewTransition>
      </body>
    </html>
  );
}
